// This file is auto-generated by vite-plugin-sveltekit-page-meta
// Do not edit manually

export interface PageMeta {
  /** 页面路径 */
  path: string;
  /** 页面标题 */
  title?: string;
  /** 权限标识 */
  permission?: string;
  /** 图标 */
  icon?: string;
  /** 分组 */
  group?: string;
  /** 排序 */
  order?: number;
  /** 是否隐藏 */
  hidden?: boolean;
  /** 面包屑 */
  breadcrumb?: string[];
  /** 自定义字段 */
  [key: string]: unknown;
}


export const pages: PageMeta[] = [
  {
    "path": "/dashboard",
    "title": "nav.title.dashboard",
    "permission": "dashboard:view",
    "icon": "tdesign:home",
    "group": "nav.group.platform",
    "order": 1
  },
  {
    "path": "/dashboard/knowledge/my-files",
    "title": "nav.title.myFiles",
    "permission": "knowledge:view",
    "icon": "tdesign:folder",
    "group": "nav.group.knowledge",
    "order": 1
  },
  {
    "path": "/dashboard/knowledge/shared-with-me",
    "title": "nav.title.sharedWithMe",
    "permission": "knowledge:view",
    "icon": "tdesign:user-transmit",
    "group": "nav.group.knowledge",
    "order": 2
  },
  {
    "path": "/dashboard/knowledge/my-shared",
    "title": "nav.title.myShared",
    "permission": "knowledge:view",
    "icon": "tdesign:share",
    "group": "nav.group.knowledge",
    "order": 3
  },
  {
    "path": "/dashboard/knowledge/favorites",
    "title": "nav.title.favorites",
    "permission": "knowledge:view",
    "icon": "tdesign:star",
    "group": "nav.group.knowledge",
    "order": 4
  },
  {
    "path": "/dashboard/contacts/chat",
    "title": "nav.title.chat",
    "icon": "tdesign:chat",
    "group": "nav.group.communication",
    "order": 5
  },
  {
    "path": "/dashboard/contacts/files",
    "title": "nav.title.conversationFiles",
    "icon": "tdesign:file",
    "group": "nav.group.communication",
    "order": 6
  },
  {
    "path": "/dashboard/ai/models",
    "title": "nav.title.models",
    "icon": "mdi:brain",
    "group": "nav.group.ai",
    "order": 10
  },
  {
    "path": "/dashboard/knowledge/my-files/[folderId]/create-text-file",
    "title": "nav.title.createTextFile",
    "permission": "knowledge:view",
    "icon": "tdesign:file-add",
    "group": "nav.group.knowledge",
    "order": 10,
    "hidden": true
  },
  {
    "path": "/dashboard/knowledge/my-files/[folderId]/edit/[fileId]",
    "title": "nav.title.editFile",
    "permission": "knowledge:view",
    "icon": "tdesign:edit",
    "group": "nav.group.knowledge",
    "order": 10,
    "hidden": true
  },
  {
    "path": "/dashboard/system/users",
    "title": "nav.title.users",
    "permission": "system:user:view",
    "icon": "tdesign:user",
    "group": "nav.group.system",
    "order": 10
  },
  {
    "path": "/dashboard/system/roles",
    "title": "nav.title.roles",
    "permission": "system:role:view",
    "icon": "tdesign:usergroup",
    "group": "nav.group.system",
    "order": 11
  },
  {
    "path": "/dashboard/system/menus",
    "title": "nav.title.menus",
    "permission": "system:menu:view",
    "icon": "tdesign:menu-application",
    "group": "nav.group.system",
    "order": 12
  },
  {
    "path": "/dashboard/system/permissions",
    "title": "nav.title.permissions",
    "permission": "system:permission:view",
    "icon": "tdesign:secured",
    "group": "nav.group.system",
    "order": 12
  },
  {
    "path": "/dashboard/system/departments",
    "title": "nav.title.departments",
    "permission": "system:dept:view",
    "icon": "tdesign:tree-square-dot",
    "group": "nav.group.system",
    "order": 13
  },
  {
    "path": "/dashboard/system/posts",
    "title": "nav.title.posts",
    "permission": "system:post:view",
    "icon": "tdesign:user-business",
    "group": "nav.group.system",
    "order": 14
  },
  {
    "path": "/dashboard/system/dicts",
    "title": "nav.title.dicts",
    "permission": "system:dict:view",
    "icon": "tdesign:book",
    "group": "nav.group.system",
    "order": 15
  },
  {
    "path": "/dashboard/system/operation-logs",
    "title": "nav.title.operationLogs",
    "permission": "system:operlog:view",
    "icon": "tdesign:history",
    "group": "nav.group.system",
    "order": 16
  },
  {
    "path": "/dashboard/system/login-logs",
    "title": "nav.title.loginLogs",
    "permission": "system:loginlog:view",
    "icon": "tdesign:login",
    "group": "nav.group.system",
    "order": 17
  },
  {
    "path": "/dashboard/ai/agents",
    "title": "nav.title.agents",
    "icon": "mdi:robot",
    "group": "nav.group.ai",
    "order": 30
  },
  {
    "path": "/dashboard/ai/user-memory",
    "title": "nav.title.userMemory",
    "icon": "mdi:head-lightbulb-outline",
    "group": "nav.group.ai",
    "order": 50
  },
  {
    "path": "/dashboard/knowledge/recycle-bin",
    "title": "nav.title.recycleBin",
    "icon": "mdi:trash-can",
    "group": "nav.group.knowledge",
    "order": 50
  },
  {
    "path": "/dashboard/ai/mcp-servers",
    "title": "nav.title.mcpServers",
    "icon": "mdi:api",
    "group": "nav.group.ai",
    "order": 60
  },
  {
    "path": "/dashboard/ai/api-keys",
    "title": "nav.title.apiKeys",
    "permission": "ai:apiKey:view",
    "icon": "mdi:key-variant",
    "group": "nav.group.ai",
    "order": 100
  },
  {
    "path": "/dashboard/preferences",
    "title": "nav.title.preferences",
    "permission": "settings:preferences:view",
    "icon": "tdesign:palette",
    "group": "nav.group.settings",
    "order": 100
  },
  {
    "path": "/dashboard/server-monitor/overview",
    "title": "nav.title.serverMonitor",
    "icon": "tdesign:server",
    "group": "nav.group.platform",
    "order": 100
  },
  {
    "path": "/dashboard/system-config",
    "title": "nav.title.systemConfig",
    "permission": "system:config:view",
    "icon": "tdesign:setting",
    "group": "nav.group.settings",
    "order": 101
  },
  {
    "path": "/dashboard/ai/data-models",
    "title": "nav.title.dataModels",
    "permission": "ai:dataModel:view",
    "icon": "mdi:database-outline",
    "group": "nav.group.ai",
    "order": 110
  },
  {
    "path": "/dashboard/ai/workflows",
    "title": "nav.title.workflows",
    "permission": "ai:workflow:view",
    "icon": "mdi:sitemap-outline",
    "group": "nav.group.ai",
    "order": 120
  },
  {
    "path": "/dashboard/dev/project-code",
    "title": "nav.title.projectCode",
    "permission": "dev:project-code:view",
    "icon": "tdesign:code",
    "group": "nav.group.dev",
    "order": 200
  },
  {
    "path": "/dashboard/dev-docs",
    "title": "nav.title.devDocs",
    "icon": "mdi:book-open-page-variant",
    "group": "nav.group.settings",
    "order": 201
  },
  {
    "path": "/dashboard/api-docs",
    "title": "nav.title.apiDocs",
    "icon": "mdi:api",
    "group": "nav.group.dev",
    "order": 302
  },
  {
    "path": "/dashboard/account",
    "title": "nav.title.account",
    "icon": "tdesign:user-circle",
    "hidden": true
  },
  {
    "path": "/dashboard/ai/workflows/[id]",
    "title": "nav.title.editWorkflow",
    "icon": "mdi:sitemap",
    "hidden": true
  },
  {
    "path": "/dashboard/contacts"
  },
  {
    "path": "/dashboard/files",
    "title": "nav.title.fileManagement",
    "permission": "knowledge:view",
    "icon": "tdesign:folder-open",
    "order": 999,
    "hidden": true
  },
  {
    "path": "/dashboard/files/[folderId]/create-text-file",
    "title": "nav.title.createTextFile",
    "permission": "knowledge:file:create",
    "icon": "tdesign:file-add",
    "hidden": true
  },
  {
    "path": "/dashboard/files/[folderId]/edit/[fileId]",
    "title": "nav.title.editFile",
    "hidden": true
  },
  {
    "path": "/dashboard/notifications",
    "title": "nav.title.notifications",
    "icon": "tdesign:notification",
    "hidden": true
  },
  {
    "path": "/dashboard/server-monitor/charts",
    "title": "nav.title.chartMonitor",
    "icon": "tdesign:chart",
    "group": "nav.group.monitor",
    "hidden": true
  },
  {
    "path": "/dashboard/server-monitor/ports",
    "title": "nav.title.portManagement",
    "icon": "tdesign:internet",
    "group": "nav.group.monitor",
    "hidden": true
  },
  {
    "path": "/dashboard/server-monitor/processes",
    "title": "nav.title.processManagement",
    "icon": "tdesign:task",
    "group": "nav.group.monitor",
    "hidden": true
  },
  {
    "path": "/dashboard/system/users/[id]",
    "title": "nav.title.editUser",
    "permission": "system:user:edit",
    "icon": "tdesign:user-setting",
    "group": "nav.group.system",
    "hidden": true
  },
  {
    "path": "/dashboard/system/users/new",
    "title": "nav.title.addUser",
    "permission": "system:user:add",
    "icon": "tdesign:user-add",
    "group": "nav.group.system",
    "hidden": true
  },
  {
    "path": "/docs/[...slug]"
  },
  {
    "path": "/login",
    "title": "nav.title.login",
    "hidden": true
  }
];

export const routeTitles: Record<string, string> = {
  '/dashboard': "nav.title.dashboard",
  '/dashboard/knowledge/my-files': "nav.title.myFiles",
  '/dashboard/knowledge/shared-with-me': "nav.title.sharedWithMe",
  '/dashboard/knowledge/my-shared': "nav.title.myShared",
  '/dashboard/knowledge/favorites': "nav.title.favorites",
  '/dashboard/contacts/chat': "nav.title.chat",
  '/dashboard/contacts/files': "nav.title.conversationFiles",
  '/dashboard/ai/models': "nav.title.models",
  '/dashboard/knowledge/my-files/[folderId]/create-text-file': "nav.title.createTextFile",
  '/dashboard/knowledge/my-files/[folderId]/edit/[fileId]': "nav.title.editFile",
  '/dashboard/system/users': "nav.title.users",
  '/dashboard/system/roles': "nav.title.roles",
  '/dashboard/system/menus': "nav.title.menus",
  '/dashboard/system/permissions': "nav.title.permissions",
  '/dashboard/system/departments': "nav.title.departments",
  '/dashboard/system/posts': "nav.title.posts",
  '/dashboard/system/dicts': "nav.title.dicts",
  '/dashboard/system/operation-logs': "nav.title.operationLogs",
  '/dashboard/system/login-logs': "nav.title.loginLogs",
  '/dashboard/ai/agents': "nav.title.agents",
  '/dashboard/ai/user-memory': "nav.title.userMemory",
  '/dashboard/knowledge/recycle-bin': "nav.title.recycleBin",
  '/dashboard/ai/mcp-servers': "nav.title.mcpServers",
  '/dashboard/ai/api-keys': "nav.title.apiKeys",
  '/dashboard/preferences': "nav.title.preferences",
  '/dashboard/server-monitor/overview': "nav.title.serverMonitor",
  '/dashboard/system-config': "nav.title.systemConfig",
  '/dashboard/ai/data-models': "nav.title.dataModels",
  '/dashboard/ai/workflows': "nav.title.workflows",
  '/dashboard/dev/project-code': "nav.title.projectCode",
  '/dashboard/dev-docs': "nav.title.devDocs",
  '/dashboard/api-docs': "nav.title.apiDocs",
  '/dashboard/account': "nav.title.account",
  '/dashboard/ai/workflows/[id]': "nav.title.editWorkflow",
  '/dashboard/files': "nav.title.fileManagement",
  '/dashboard/files/[folderId]/create-text-file': "nav.title.createTextFile",
  '/dashboard/files/[folderId]/edit/[fileId]': "nav.title.editFile",
  '/dashboard/notifications': "nav.title.notifications",
  '/dashboard/server-monitor/charts': "nav.title.chartMonitor",
  '/dashboard/server-monitor/ports': "nav.title.portManagement",
  '/dashboard/server-monitor/processes': "nav.title.processManagement",
  '/dashboard/system/users/[id]': "nav.title.editUser",
  '/dashboard/system/users/new': "nav.title.addUser",
  '/login': "nav.title.login"
};

export const groupedPages: Record<string, PageMeta[]> = {
  "nav.group.platform": [
    {
      "path": "/dashboard",
      "title": "nav.title.dashboard",
      "permission": "dashboard:view",
      "icon": "tdesign:home",
      "group": "nav.group.platform",
      "order": 1
    },
    {
      "path": "/dashboard/server-monitor/overview",
      "title": "nav.title.serverMonitor",
      "icon": "tdesign:server",
      "group": "nav.group.platform",
      "order": 100
    }
  ],
  "nav.group.knowledge": [
    {
      "path": "/dashboard/knowledge/my-files",
      "title": "nav.title.myFiles",
      "permission": "knowledge:view",
      "icon": "tdesign:folder",
      "group": "nav.group.knowledge",
      "order": 1
    },
    {
      "path": "/dashboard/knowledge/shared-with-me",
      "title": "nav.title.sharedWithMe",
      "permission": "knowledge:view",
      "icon": "tdesign:user-transmit",
      "group": "nav.group.knowledge",
      "order": 2
    },
    {
      "path": "/dashboard/knowledge/my-shared",
      "title": "nav.title.myShared",
      "permission": "knowledge:view",
      "icon": "tdesign:share",
      "group": "nav.group.knowledge",
      "order": 3
    },
    {
      "path": "/dashboard/knowledge/favorites",
      "title": "nav.title.favorites",
      "permission": "knowledge:view",
      "icon": "tdesign:star",
      "group": "nav.group.knowledge",
      "order": 4
    },
    {
      "path": "/dashboard/knowledge/my-files/[folderId]/create-text-file",
      "title": "nav.title.createTextFile",
      "permission": "knowledge:view",
      "icon": "tdesign:file-add",
      "group": "nav.group.knowledge",
      "order": 10,
      "hidden": true
    },
    {
      "path": "/dashboard/knowledge/my-files/[folderId]/edit/[fileId]",
      "title": "nav.title.editFile",
      "permission": "knowledge:view",
      "icon": "tdesign:edit",
      "group": "nav.group.knowledge",
      "order": 10,
      "hidden": true
    },
    {
      "path": "/dashboard/knowledge/recycle-bin",
      "title": "nav.title.recycleBin",
      "icon": "mdi:trash-can",
      "group": "nav.group.knowledge",
      "order": 50
    }
  ],
  "nav.group.communication": [
    {
      "path": "/dashboard/contacts/chat",
      "title": "nav.title.chat",
      "icon": "tdesign:chat",
      "group": "nav.group.communication",
      "order": 5
    },
    {
      "path": "/dashboard/contacts/files",
      "title": "nav.title.conversationFiles",
      "icon": "tdesign:file",
      "group": "nav.group.communication",
      "order": 6
    }
  ],
  "nav.group.ai": [
    {
      "path": "/dashboard/ai/models",
      "title": "nav.title.models",
      "icon": "mdi:brain",
      "group": "nav.group.ai",
      "order": 10
    },
    {
      "path": "/dashboard/ai/agents",
      "title": "nav.title.agents",
      "icon": "mdi:robot",
      "group": "nav.group.ai",
      "order": 30
    },
    {
      "path": "/dashboard/ai/user-memory",
      "title": "nav.title.userMemory",
      "icon": "mdi:head-lightbulb-outline",
      "group": "nav.group.ai",
      "order": 50
    },
    {
      "path": "/dashboard/ai/mcp-servers",
      "title": "nav.title.mcpServers",
      "icon": "mdi:api",
      "group": "nav.group.ai",
      "order": 60
    },
    {
      "path": "/dashboard/ai/api-keys",
      "title": "nav.title.apiKeys",
      "permission": "ai:apiKey:view",
      "icon": "mdi:key-variant",
      "group": "nav.group.ai",
      "order": 100
    },
    {
      "path": "/dashboard/ai/data-models",
      "title": "nav.title.dataModels",
      "permission": "ai:dataModel:view",
      "icon": "mdi:database-outline",
      "group": "nav.group.ai",
      "order": 110
    },
    {
      "path": "/dashboard/ai/workflows",
      "title": "nav.title.workflows",
      "permission": "ai:workflow:view",
      "icon": "mdi:sitemap-outline",
      "group": "nav.group.ai",
      "order": 120
    }
  ],
  "nav.group.system": [
    {
      "path": "/dashboard/system/users",
      "title": "nav.title.users",
      "permission": "system:user:view",
      "icon": "tdesign:user",
      "group": "nav.group.system",
      "order": 10
    },
    {
      "path": "/dashboard/system/roles",
      "title": "nav.title.roles",
      "permission": "system:role:view",
      "icon": "tdesign:usergroup",
      "group": "nav.group.system",
      "order": 11
    },
    {
      "path": "/dashboard/system/menus",
      "title": "nav.title.menus",
      "permission": "system:menu:view",
      "icon": "tdesign:menu-application",
      "group": "nav.group.system",
      "order": 12
    },
    {
      "path": "/dashboard/system/permissions",
      "title": "nav.title.permissions",
      "permission": "system:permission:view",
      "icon": "tdesign:secured",
      "group": "nav.group.system",
      "order": 12
    },
    {
      "path": "/dashboard/system/departments",
      "title": "nav.title.departments",
      "permission": "system:dept:view",
      "icon": "tdesign:tree-square-dot",
      "group": "nav.group.system",
      "order": 13
    },
    {
      "path": "/dashboard/system/posts",
      "title": "nav.title.posts",
      "permission": "system:post:view",
      "icon": "tdesign:user-business",
      "group": "nav.group.system",
      "order": 14
    },
    {
      "path": "/dashboard/system/dicts",
      "title": "nav.title.dicts",
      "permission": "system:dict:view",
      "icon": "tdesign:book",
      "group": "nav.group.system",
      "order": 15
    },
    {
      "path": "/dashboard/system/operation-logs",
      "title": "nav.title.operationLogs",
      "permission": "system:operlog:view",
      "icon": "tdesign:history",
      "group": "nav.group.system",
      "order": 16
    },
    {
      "path": "/dashboard/system/login-logs",
      "title": "nav.title.loginLogs",
      "permission": "system:loginlog:view",
      "icon": "tdesign:login",
      "group": "nav.group.system",
      "order": 17
    },
    {
      "path": "/dashboard/system/users/[id]",
      "title": "nav.title.editUser",
      "permission": "system:user:edit",
      "icon": "tdesign:user-setting",
      "group": "nav.group.system",
      "hidden": true
    },
    {
      "path": "/dashboard/system/users/new",
      "title": "nav.title.addUser",
      "permission": "system:user:add",
      "icon": "tdesign:user-add",
      "group": "nav.group.system",
      "hidden": true
    }
  ],
  "nav.group.settings": [
    {
      "path": "/dashboard/preferences",
      "title": "nav.title.preferences",
      "permission": "settings:preferences:view",
      "icon": "tdesign:palette",
      "group": "nav.group.settings",
      "order": 100
    },
    {
      "path": "/dashboard/system-config",
      "title": "nav.title.systemConfig",
      "permission": "system:config:view",
      "icon": "tdesign:setting",
      "group": "nav.group.settings",
      "order": 101
    },
    {
      "path": "/dashboard/dev-docs",
      "title": "nav.title.devDocs",
      "icon": "mdi:book-open-page-variant",
      "group": "nav.group.settings",
      "order": 201
    }
  ],
  "nav.group.dev": [
    {
      "path": "/dashboard/dev/project-code",
      "title": "nav.title.projectCode",
      "permission": "dev:project-code:view",
      "icon": "tdesign:code",
      "group": "nav.group.dev",
      "order": 200
    },
    {
      "path": "/dashboard/api-docs",
      "title": "nav.title.apiDocs",
      "icon": "mdi:api",
      "group": "nav.group.dev",
      "order": 302
    }
  ],
  "default": [
    {
      "path": "/dashboard/account",
      "title": "nav.title.account",
      "icon": "tdesign:user-circle",
      "hidden": true
    },
    {
      "path": "/dashboard/ai/workflows/[id]",
      "title": "nav.title.editWorkflow",
      "icon": "mdi:sitemap",
      "hidden": true
    },
    {
      "path": "/dashboard/contacts"
    },
    {
      "path": "/dashboard/files",
      "title": "nav.title.fileManagement",
      "permission": "knowledge:view",
      "icon": "tdesign:folder-open",
      "order": 999,
      "hidden": true
    },
    {
      "path": "/dashboard/files/[folderId]/create-text-file",
      "title": "nav.title.createTextFile",
      "permission": "knowledge:file:create",
      "icon": "tdesign:file-add",
      "hidden": true
    },
    {
      "path": "/dashboard/files/[folderId]/edit/[fileId]",
      "title": "nav.title.editFile",
      "hidden": true
    },
    {
      "path": "/dashboard/notifications",
      "title": "nav.title.notifications",
      "icon": "tdesign:notification",
      "hidden": true
    },
    {
      "path": "/docs/[...slug]"
    },
    {
      "path": "/login",
      "title": "nav.title.login",
      "hidden": true
    }
  ],
  "nav.group.monitor": [
    {
      "path": "/dashboard/server-monitor/charts",
      "title": "nav.title.chartMonitor",
      "icon": "tdesign:chart",
      "group": "nav.group.monitor",
      "hidden": true
    },
    {
      "path": "/dashboard/server-monitor/ports",
      "title": "nav.title.portManagement",
      "icon": "tdesign:internet",
      "group": "nav.group.monitor",
      "hidden": true
    },
    {
      "path": "/dashboard/server-monitor/processes",
      "title": "nav.title.processManagement",
      "icon": "tdesign:task",
      "group": "nav.group.monitor",
      "hidden": true
    }
  ]
};

/** 所有页面权限列表 */
export const permissions = [
  "dashboard:view",
  "knowledge:view",
  "system:user:view",
  "system:role:view",
  "system:menu:view",
  "system:permission:view",
  "system:dept:view",
  "system:post:view",
  "system:dict:view",
  "system:operlog:view",
  "system:loginlog:view",
  "ai:apiKey:view",
  "settings:preferences:view",
  "system:config:view",
  "ai:dataModel:view",
  "ai:workflow:view",
  "dev:project-code:view",
  "knowledge:file:create",
  "system:user:edit",
  "system:user:add"
] as const;

/** 权限类型 */
export type Permission = typeof permissions[number];

/** 权限与路由映射 */
export const permissionRouteMap: Record<string, { path: string; title?: string }> = {
  "dashboard:view": { path: "/dashboard", title: "nav.title.dashboard" },
  "knowledge:view": { path: "/dashboard/knowledge/my-files", title: "nav.title.myFiles" },
  "knowledge:view": { path: "/dashboard/knowledge/shared-with-me", title: "nav.title.sharedWithMe" },
  "knowledge:view": { path: "/dashboard/knowledge/my-shared", title: "nav.title.myShared" },
  "knowledge:view": { path: "/dashboard/knowledge/favorites", title: "nav.title.favorites" },
  "knowledge:view": { path: "/dashboard/knowledge/my-files/[folderId]/create-text-file", title: "nav.title.createTextFile" },
  "knowledge:view": { path: "/dashboard/knowledge/my-files/[folderId]/edit/[fileId]", title: "nav.title.editFile" },
  "system:user:view": { path: "/dashboard/system/users", title: "nav.title.users" },
  "system:role:view": { path: "/dashboard/system/roles", title: "nav.title.roles" },
  "system:menu:view": { path: "/dashboard/system/menus", title: "nav.title.menus" },
  "system:permission:view": { path: "/dashboard/system/permissions", title: "nav.title.permissions" },
  "system:dept:view": { path: "/dashboard/system/departments", title: "nav.title.departments" },
  "system:post:view": { path: "/dashboard/system/posts", title: "nav.title.posts" },
  "system:dict:view": { path: "/dashboard/system/dicts", title: "nav.title.dicts" },
  "system:operlog:view": { path: "/dashboard/system/operation-logs", title: "nav.title.operationLogs" },
  "system:loginlog:view": { path: "/dashboard/system/login-logs", title: "nav.title.loginLogs" },
  "ai:apiKey:view": { path: "/dashboard/ai/api-keys", title: "nav.title.apiKeys" },
  "settings:preferences:view": { path: "/dashboard/preferences", title: "nav.title.preferences" },
  "system:config:view": { path: "/dashboard/system-config", title: "nav.title.systemConfig" },
  "ai:dataModel:view": { path: "/dashboard/ai/data-models", title: "nav.title.dataModels" },
  "ai:workflow:view": { path: "/dashboard/ai/workflows", title: "nav.title.workflows" },
  "dev:project-code:view": { path: "/dashboard/dev/project-code", title: "nav.title.projectCode" },
  "knowledge:view": { path: "/dashboard/files", title: "nav.title.fileManagement" },
  "knowledge:file:create": { path: "/dashboard/files/[folderId]/create-text-file", title: "nav.title.createTextFile" },
  "system:user:edit": { path: "/dashboard/system/users/[id]", title: "nav.title.editUser" },
  "system:user:add": { path: "/dashboard/system/users/new", title: "nav.title.addUser" }
};

/** 路由与权限映射 */
export const routePermissionMap: Record<string, string> = {
  "/dashboard": "dashboard:view",
  "/dashboard/knowledge/my-files": "knowledge:view",
  "/dashboard/knowledge/shared-with-me": "knowledge:view",
  "/dashboard/knowledge/my-shared": "knowledge:view",
  "/dashboard/knowledge/favorites": "knowledge:view",
  "/dashboard/knowledge/my-files/[folderId]/create-text-file": "knowledge:view",
  "/dashboard/knowledge/my-files/[folderId]/edit/[fileId]": "knowledge:view",
  "/dashboard/system/users": "system:user:view",
  "/dashboard/system/roles": "system:role:view",
  "/dashboard/system/menus": "system:menu:view",
  "/dashboard/system/permissions": "system:permission:view",
  "/dashboard/system/departments": "system:dept:view",
  "/dashboard/system/posts": "system:post:view",
  "/dashboard/system/dicts": "system:dict:view",
  "/dashboard/system/operation-logs": "system:operlog:view",
  "/dashboard/system/login-logs": "system:loginlog:view",
  "/dashboard/ai/api-keys": "ai:apiKey:view",
  "/dashboard/preferences": "settings:preferences:view",
  "/dashboard/system-config": "system:config:view",
  "/dashboard/ai/data-models": "ai:dataModel:view",
  "/dashboard/ai/workflows": "ai:workflow:view",
  "/dashboard/dev/project-code": "dev:project-code:view",
  "/dashboard/files": "knowledge:view",
  "/dashboard/files/[folderId]/create-text-file": "knowledge:file:create",
  "/dashboard/system/users/[id]": "system:user:edit",
  "/dashboard/system/users/new": "system:user:add"
};
