// This file is auto-generated by vite-plugin-sveltekit-page-meta
// Do not edit manually

export interface PageMeta {
  /** 页面路径 */
  path: string;
  /** 页面标题 */
  title?: string;
  /** 权限标识 */
  permission?: string;
  /** 图标 */
  icon?: string;
  /** 分组 */
  group?: string;
  /** 排序 */
  order?: number;
  /** 是否隐藏 */
  hidden?: boolean;
  /** 面包屑 */
  breadcrumb?: string[];
  /** 自定义字段 */
  [key: string]: unknown;
}


export const pages: PageMeta[] = [
  {
    "path": "/dashboard",
    "title": "首页",
    "permission": "dashboard:view",
    "icon": "tdesign:home",
    "group": "平台",
    "order": 1
  },
  {
    "path": "/dashboard/files",
    "title": "知识库",
    "permission": "knowledge:view",
    "icon": "tdesign:folder-open",
    "group": "平台",
    "order": 3
  },
  {
    "path": "/dashboard/contacts",
    "title": "联系人",
    "icon": "tdesign:user-talk",
    "group": "沟通",
    "order": 5
  },
  {
    "path": "/dashboard/ai/models",
    "title": "模型管理",
    "icon": "mdi:brain",
    "group": "智能体",
    "order": 10
  },
  {
    "path": "/dashboard/system/users",
    "title": "用户管理",
    "permission": "system:user:view",
    "icon": "tdesign:user",
    "group": "系统管理",
    "order": 10
  },
  {
    "path": "/dashboard/system/roles",
    "title": "角色管理",
    "permission": "system:role:view",
    "icon": "tdesign:usergroup",
    "group": "系统管理",
    "order": 11
  },
  {
    "path": "/dashboard/system/menus",
    "title": "菜单管理",
    "permission": "system:menu:view",
    "icon": "tdesign:menu-application",
    "group": "系统管理",
    "order": 12
  },
  {
    "path": "/dashboard/system/departments",
    "title": "部门管理",
    "permission": "system:dept:view",
    "icon": "tdesign:tree-square-dot",
    "group": "系统管理",
    "order": 13
  },
  {
    "path": "/dashboard/system/posts",
    "title": "岗位管理",
    "permission": "system:post:view",
    "icon": "tdesign:user-business",
    "group": "系统管理",
    "order": 14
  },
  {
    "path": "/dashboard/system/dicts",
    "title": "字典管理",
    "permission": "system:dict:view",
    "icon": "tdesign:book",
    "group": "系统管理",
    "order": 15
  },
  {
    "path": "/dashboard/system/operation-logs",
    "title": "操作日志",
    "permission": "system:operlog:view",
    "icon": "tdesign:history",
    "group": "系统管理",
    "order": 16
  },
  {
    "path": "/dashboard/system/login-logs",
    "title": "登录日志",
    "permission": "system:loginlog:view",
    "icon": "tdesign:login",
    "group": "系统管理",
    "order": 17
  },
  {
    "path": "/dashboard/ai/tools",
    "title": "工具管理",
    "icon": "mdi:tools",
    "group": "智能体",
    "order": 20
  },
  {
    "path": "/dashboard/ai/agents",
    "title": "智能体管理",
    "icon": "mdi:robot",
    "group": "智能体",
    "order": 30
  },
  {
    "path": "/dashboard/ai/skills",
    "title": "技能管理",
    "icon": "mdi:lightning-bolt",
    "group": "智能体",
    "order": 40
  },
  {
    "path": "/dashboard/preferences",
    "title": "个性化",
    "permission": "settings:preferences:view",
    "icon": "tdesign:palette",
    "group": "系统设置",
    "order": 100
  },
  {
    "path": "/dashboard/system-config",
    "title": "系统参数",
    "permission": "system:config:view",
    "icon": "tdesign:setting",
    "group": "系统设置",
    "order": 101
  },
  {
    "path": "/dashboard/ai/tools/[id]",
    "title": "编辑工具",
    "icon": "mdi:tools",
    "group": "智能体",
    "hidden": true
  },
  {
    "path": "/dashboard/ai/tools/new",
    "title": "新建工具",
    "icon": "mdi:tools",
    "group": "智能体",
    "hidden": true
  },
  {
    "path": "/dashboard/files/[folderId]/create-text-file",
    "title": "新建文本文件",
    "permission": "knowledge:file:create",
    "icon": "tdesign:file-add",
    "hidden": true
  },
  {
    "path": "/dashboard/files/[folderId]/edit/[fileId]",
    "title": "编辑文件",
    "hidden": true
  },
  {
    "path": "/dashboard/system/users/[id]",
    "title": "编辑用户",
    "permission": "system:user:edit",
    "icon": "tdesign:user-setting",
    "group": "系统管理",
    "hidden": true
  },
  {
    "path": "/dashboard/system/users/new",
    "title": "新增用户",
    "permission": "system:user:add",
    "icon": "tdesign:user-add",
    "group": "系统管理",
    "hidden": true
  },
  {
    "path": "/login",
    "title": "登录",
    "hidden": true
  }
];

export const routeTitles: Record<string, string> = {
  '/dashboard': "首页",
  '/dashboard/files': "知识库",
  '/dashboard/contacts': "联系人",
  '/dashboard/ai/models': "模型管理",
  '/dashboard/system/users': "用户管理",
  '/dashboard/system/roles': "角色管理",
  '/dashboard/system/menus': "菜单管理",
  '/dashboard/system/departments': "部门管理",
  '/dashboard/system/posts': "岗位管理",
  '/dashboard/system/dicts': "字典管理",
  '/dashboard/system/operation-logs': "操作日志",
  '/dashboard/system/login-logs': "登录日志",
  '/dashboard/ai/tools': "工具管理",
  '/dashboard/ai/agents': "智能体管理",
  '/dashboard/ai/skills': "技能管理",
  '/dashboard/preferences': "个性化",
  '/dashboard/system-config': "系统参数",
  '/dashboard/ai/tools/[id]': "编辑工具",
  '/dashboard/ai/tools/new': "新建工具",
  '/dashboard/files/[folderId]/create-text-file': "新建文本文件",
  '/dashboard/files/[folderId]/edit/[fileId]': "编辑文件",
  '/dashboard/system/users/[id]': "编辑用户",
  '/dashboard/system/users/new': "新增用户",
  '/login': "登录"
};

export const groupedPages: Record<string, PageMeta[]> = {
  "平台": [
    {
      "path": "/dashboard",
      "title": "首页",
      "permission": "dashboard:view",
      "icon": "tdesign:home",
      "group": "平台",
      "order": 1
    },
    {
      "path": "/dashboard/files",
      "title": "知识库",
      "permission": "knowledge:view",
      "icon": "tdesign:folder-open",
      "group": "平台",
      "order": 3
    }
  ],
  "沟通": [
    {
      "path": "/dashboard/contacts",
      "title": "联系人",
      "icon": "tdesign:user-talk",
      "group": "沟通",
      "order": 5
    }
  ],
  "智能体": [
    {
      "path": "/dashboard/ai/models",
      "title": "模型管理",
      "icon": "mdi:brain",
      "group": "智能体",
      "order": 10
    },
    {
      "path": "/dashboard/ai/tools",
      "title": "工具管理",
      "icon": "mdi:tools",
      "group": "智能体",
      "order": 20
    },
    {
      "path": "/dashboard/ai/agents",
      "title": "智能体管理",
      "icon": "mdi:robot",
      "group": "智能体",
      "order": 30
    },
    {
      "path": "/dashboard/ai/skills",
      "title": "技能管理",
      "icon": "mdi:lightning-bolt",
      "group": "智能体",
      "order": 40
    },
    {
      "path": "/dashboard/ai/tools/[id]",
      "title": "编辑工具",
      "icon": "mdi:tools",
      "group": "智能体",
      "hidden": true
    },
    {
      "path": "/dashboard/ai/tools/new",
      "title": "新建工具",
      "icon": "mdi:tools",
      "group": "智能体",
      "hidden": true
    }
  ],
  "系统管理": [
    {
      "path": "/dashboard/system/users",
      "title": "用户管理",
      "permission": "system:user:view",
      "icon": "tdesign:user",
      "group": "系统管理",
      "order": 10
    },
    {
      "path": "/dashboard/system/roles",
      "title": "角色管理",
      "permission": "system:role:view",
      "icon": "tdesign:usergroup",
      "group": "系统管理",
      "order": 11
    },
    {
      "path": "/dashboard/system/menus",
      "title": "菜单管理",
      "permission": "system:menu:view",
      "icon": "tdesign:menu-application",
      "group": "系统管理",
      "order": 12
    },
    {
      "path": "/dashboard/system/departments",
      "title": "部门管理",
      "permission": "system:dept:view",
      "icon": "tdesign:tree-square-dot",
      "group": "系统管理",
      "order": 13
    },
    {
      "path": "/dashboard/system/posts",
      "title": "岗位管理",
      "permission": "system:post:view",
      "icon": "tdesign:user-business",
      "group": "系统管理",
      "order": 14
    },
    {
      "path": "/dashboard/system/dicts",
      "title": "字典管理",
      "permission": "system:dict:view",
      "icon": "tdesign:book",
      "group": "系统管理",
      "order": 15
    },
    {
      "path": "/dashboard/system/operation-logs",
      "title": "操作日志",
      "permission": "system:operlog:view",
      "icon": "tdesign:history",
      "group": "系统管理",
      "order": 16
    },
    {
      "path": "/dashboard/system/login-logs",
      "title": "登录日志",
      "permission": "system:loginlog:view",
      "icon": "tdesign:login",
      "group": "系统管理",
      "order": 17
    },
    {
      "path": "/dashboard/system/users/[id]",
      "title": "编辑用户",
      "permission": "system:user:edit",
      "icon": "tdesign:user-setting",
      "group": "系统管理",
      "hidden": true
    },
    {
      "path": "/dashboard/system/users/new",
      "title": "新增用户",
      "permission": "system:user:add",
      "icon": "tdesign:user-add",
      "group": "系统管理",
      "hidden": true
    }
  ],
  "系统设置": [
    {
      "path": "/dashboard/preferences",
      "title": "个性化",
      "permission": "settings:preferences:view",
      "icon": "tdesign:palette",
      "group": "系统设置",
      "order": 100
    },
    {
      "path": "/dashboard/system-config",
      "title": "系统参数",
      "permission": "system:config:view",
      "icon": "tdesign:setting",
      "group": "系统设置",
      "order": 101
    }
  ],
  "default": [
    {
      "path": "/dashboard/files/[folderId]/create-text-file",
      "title": "新建文本文件",
      "permission": "knowledge:file:create",
      "icon": "tdesign:file-add",
      "hidden": true
    },
    {
      "path": "/dashboard/files/[folderId]/edit/[fileId]",
      "title": "编辑文件",
      "hidden": true
    },
    {
      "path": "/login",
      "title": "登录",
      "hidden": true
    }
  ]
};

/** 所有页面权限列表 */
export const permissions = [
  "dashboard:view",
  "knowledge:view",
  "system:user:view",
  "system:role:view",
  "system:menu:view",
  "system:dept:view",
  "system:post:view",
  "system:dict:view",
  "system:operlog:view",
  "system:loginlog:view",
  "settings:preferences:view",
  "system:config:view",
  "knowledge:file:create",
  "system:user:edit",
  "system:user:add"
] as const;

/** 权限类型 */
export type Permission = typeof permissions[number];

/** 权限与路由映射 */
export const permissionRouteMap: Record<string, { path: string; title?: string }> = {
  "dashboard:view": { path: "/dashboard", title: "首页" },
  "knowledge:view": { path: "/dashboard/files", title: "知识库" },
  "system:user:view": { path: "/dashboard/system/users", title: "用户管理" },
  "system:role:view": { path: "/dashboard/system/roles", title: "角色管理" },
  "system:menu:view": { path: "/dashboard/system/menus", title: "菜单管理" },
  "system:dept:view": { path: "/dashboard/system/departments", title: "部门管理" },
  "system:post:view": { path: "/dashboard/system/posts", title: "岗位管理" },
  "system:dict:view": { path: "/dashboard/system/dicts", title: "字典管理" },
  "system:operlog:view": { path: "/dashboard/system/operation-logs", title: "操作日志" },
  "system:loginlog:view": { path: "/dashboard/system/login-logs", title: "登录日志" },
  "settings:preferences:view": { path: "/dashboard/preferences", title: "个性化" },
  "system:config:view": { path: "/dashboard/system-config", title: "系统参数" },
  "knowledge:file:create": { path: "/dashboard/files/[folderId]/create-text-file", title: "新建文本文件" },
  "system:user:edit": { path: "/dashboard/system/users/[id]", title: "编辑用户" },
  "system:user:add": { path: "/dashboard/system/users/new", title: "新增用户" }
};

/** 路由与权限映射 */
export const routePermissionMap: Record<string, string> = {
  "/dashboard": "dashboard:view",
  "/dashboard/files": "knowledge:view",
  "/dashboard/system/users": "system:user:view",
  "/dashboard/system/roles": "system:role:view",
  "/dashboard/system/menus": "system:menu:view",
  "/dashboard/system/departments": "system:dept:view",
  "/dashboard/system/posts": "system:post:view",
  "/dashboard/system/dicts": "system:dict:view",
  "/dashboard/system/operation-logs": "system:operlog:view",
  "/dashboard/system/login-logs": "system:loginlog:view",
  "/dashboard/preferences": "settings:preferences:view",
  "/dashboard/system-config": "system:config:view",
  "/dashboard/files/[folderId]/create-text-file": "knowledge:file:create",
  "/dashboard/system/users/[id]": "system:user:edit",
  "/dashboard/system/users/new": "system:user:add"
};
