import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname } from 'node:path';
import type { ParsedPage, PluginOptions } from './types';

/**
 * 生成 TypeScript 类型定义
 */
function generateTypeDefinition(): string {
  return `export interface PageMeta {
  /** 页面路径 */
  path: string;
  /** 页面标题 */
  title?: string;
  /** 权限标识 */
  permission?: string;
  /** 图标 */
  icon?: string;
  /** 分组 */
  group?: string;
  /** 排序 */
  order?: number;
  /** 是否隐藏 */
  hidden?: boolean;
  /** 面包屑 */
  breadcrumb?: string[];
  /** 自定义字段 */
  [key: string]: unknown;
}

`;
}

/**
 * 生成页面数组代码
 */
function generatePagesArray(pages: ParsedPage[]): string {
  const items = pages.map((page) => {
    const meta = {
      path: page.routePath,
      ...page.meta,
    };
    return `  ${JSON.stringify(meta, null, 2).replace(/\n/g, '\n  ')}`;
  });

  return `export const pages: PageMeta[] = [
${items.join(',\n')}
];`;
}

/**
 * 生成路由映射
 */
function generateRouteMap(pages: ParsedPage[]): string {
  const entries = pages
    .filter((p) => p.meta.title)
    .map((p) => `  '${p.routePath}': ${JSON.stringify(p.meta.title)}`);

  return `
export const routeTitles: Record<string, string> = {
${entries.join(',\n')}
};`;
}

/**
 * 生成分组结构
 */
function generateGroupedPages(pages: ParsedPage[]): string {
  const groups: Record<string, ParsedPage[]> = {};

  for (const page of pages) {
    const group = (page.meta.group as string) || 'default';
    if (!groups[group]) {
      groups[group] = [];
    }
    groups[group].push(page);
  }

  const groupEntries = Object.entries(groups).map(([group, groupPages]) => {
    const items = groupPages.map((p) => ({
      path: p.routePath,
      ...p.meta,
    }));
    return `  ${JSON.stringify(group)}: ${JSON.stringify(items, null, 2).replace(/\n/g, '\n  ')}`;
  });

  return `
export const groupedPages: Record<string, PageMeta[]> = {
${groupEntries.join(',\n')}
};`;
}

/**
 * 生成权限列表
 */
function generatePermissions(pages: ParsedPage[]): string {
  const permissions = pages
    .filter((p) => p.meta.permission)
    .map((p) => ({
      permission: p.meta.permission as string,
      path: p.routePath,
      title: p.meta.title as string | undefined,
    }));

  const permissionSet = [...new Set(permissions.map((p) => p.permission))];

  return `
/** 所有页面权限列表 */
export const permissions = ${JSON.stringify(permissionSet, null, 2)} as const;

/** 权限类型 */
export type Permission = typeof permissions[number];

/** 权限与路由映射 */
export const permissionRouteMap: Record<string, { path: string; title?: string }> = {
${permissions.map((p) => `  ${JSON.stringify(p.permission)}: { path: ${JSON.stringify(p.path)}, title: ${JSON.stringify(p.title)} }`).join(',\n')}
};

/** 路由与权限映射 */
export const routePermissionMap: Record<string, string> = {
${permissions.map((p) => `  ${JSON.stringify(p.path)}: ${JSON.stringify(p.permission)}`).join(',\n')}
};`;
}

/**
 * 生成输出文件
 */
export function generateOutput(pages: ParsedPage[], options: PluginOptions): string {
  const { generateTypes = true } = options;

  const parts: string[] = [
    '// This file is auto-generated by vite-plugin-sveltekit-page-meta',
    '// Do not edit manually',
    '',
  ];

  if (generateTypes) {
    parts.push(generateTypeDefinition());
  }

  parts.push(generatePagesArray(pages));
  parts.push(generateRouteMap(pages));
  parts.push(generateGroupedPages(pages));
  parts.push(generatePermissions(pages));
  parts.push('');

  return parts.join('\n');
}

/**
 * 写入输出文件
 */
export function writeOutput(content: string, outputPath: string): void {
  // 确保目录存在
  mkdirSync(dirname(outputPath), { recursive: true });

  // 写入文件
  writeFileSync(outputPath, content, 'utf-8');
}
