/**
 * STDIO MCP Server 生成器
 * 生成独立的 JS 文件，可通过 node 运行
 */

import { Elysia, t } from "elysia";
import { eq } from "drizzle-orm";
import db from "@qiyu-allinai/db/connect";
import { mcpServer } from "@qiyu-allinai/db/entities/ai";
import { actionsMap } from "../../../config";

// Action 信息类型
interface ActionInfo {
  name: string;
  displayName: string;
  description: string;
  method: string;
  path: string;
  bodySchema: unknown;
  paramsSchema: unknown;
  querySchema: unknown;
}

/**
 * 构建 actions 信息列表
 */
function buildActionInfos(actionNames: string[]): ActionInfo[] {
  const actionInfos: ActionInfo[] = [];
  for (const actionName of actionNames) {
    const action = actionsMap.get(actionName);
    if (!action) continue;
    actionInfos.push({
      name: action.meta.name,
      displayName: action.meta.displayName,
      description: action.meta.description,
      method: action.meta.method,
      path: action.meta.path,
      bodySchema: action.schemas.bodySchema || null,
      paramsSchema: action.schemas.paramsSchema || null,
      querySchema: action.schemas.querySchema || null,
    });
  }
  return actionInfos;
}

/**
 * 生成 STDIO MCP 服务器 JS 文件
 */
function generateStdioServerJs(
  serverName: string,
  displayName: string,
  description: string | null,
  baseUrl: string,
  isPublic: boolean,
  actions: ActionInfo[]
): string {
  // 生成 tools 定义
  const toolsDefinition = actions.map(action => {
    const properties: Record<string, unknown> = {};
    if (action.paramsSchema) properties.params = action.paramsSchema;
    if (action.querySchema) properties.query = action.querySchema;
    if (action.bodySchema) properties.body = action.bodySchema;

    return `  {
    name: ${JSON.stringify(action.name)},
    description: ${JSON.stringify(action.description || action.displayName)},
    inputSchema: {
      type: "object",
      properties: ${JSON.stringify(properties, null, 6).split('\n').map((l, i) => i === 0 ? l : '      ' + l).join('\n')},
    },
  }`;
  }).join(',\n');

  // 生成 action 处理映射
  const actionHandlers = actions.map(action => {
    const pathTemplate = action.path.replace(/:(\w+)/g, '${params.$1}');
    const hasBody = action.method !== 'GET' && action.method !== 'DELETE';

    return `    case ${JSON.stringify(action.name)}: {
      const { params = {}, query = {}, body } = args;
      let url = \`\${BASE_URL}${pathTemplate}\`;
      const queryStr = new URLSearchParams(query).toString();
      if (queryStr) url += '?' + queryStr;
      
      const res = await fetch(url, {
        method: ${JSON.stringify(action.method)},
        headers,
        ${hasBody ? 'body: body ? JSON.stringify(body) : undefined,' : ''}
      });
      return await res.json();
    }`;
  }).join('\n');

  return `#!/usr/bin/env node
/**
 * ${displayName} - STDIO MCP Server
 * ${description || 'MCP Server generated by QiyuAI'}
 * 
 * 使用方式:
 *   node ${serverName}-mcp-server.js
 * 
 * 环境变量:
 *   QIYUAI_AUTH_TOKEN - 认证 Token${isPublic ? ' (可选，此服务为公开服务)' : ' (必需)'}
 */

import { Server } from "@modelcontextprotocol/sdk/server/index.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import {
  CallToolRequestSchema,
  ListToolsRequestSchema,
} from "@modelcontextprotocol/sdk/types.js";

const BASE_URL = ${JSON.stringify(baseUrl)};
const IS_PUBLIC = ${isPublic};
const AUTH_TOKEN = process.env.QIYUAI_AUTH_TOKEN || '';

// 工具定义
const TOOLS = [
${toolsDefinition}
];

// 创建 MCP Server
const server = new Server(
  { name: ${JSON.stringify(serverName)}, version: "1.0.0" },
  { capabilities: { tools: {} } }
);

// 列出工具
server.setRequestHandler(ListToolsRequestSchema, async () => {
  return { tools: TOOLS };
});

// 调用工具
server.setRequestHandler(CallToolRequestSchema, async (request) => {
  const { name, arguments: args = {} } = request.params;
  
  const headers = { "Content-Type": "application/json" };
  if (!IS_PUBLIC && AUTH_TOKEN) {
    headers["Authorization"] = \`Bearer \${AUTH_TOKEN}\`;
  }

  try {
    let result;
    switch (name) {
${actionHandlers}
      default:
        throw new Error(\`Unknown tool: \${name}\`);
    }

    return {
      content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
    };
  } catch (error) {
    return {
      content: [{ type: "text", text: \`Error: \${error.message}\` }],
      isError: true,
    };
  }
});

// 启动服务器
async function main() {
  if (!IS_PUBLIC && !AUTH_TOKEN) {
    console.error("Warning: QIYUAI_AUTH_TOKEN not set. API calls may fail.");
  }
  
  const transport = new StdioServerTransport();
  await server.connect(transport);
  console.error(\`${displayName} MCP Server running on stdio\`);
}

main().catch(console.error);
`;
}

/**
 * 生成使用说明
 */
function generateUsage(
  serverName: string,
  displayName: string,
  isPublic: boolean,
  configJson: string,
  actionInfos: ActionInfo[]
): string {
  return `# ${displayName} - STDIO MCP Server

## 安装使用

1. 下载 \`${serverName}-mcp-server.js\` 文件
2. 安装依赖: \`npm install @modelcontextprotocol/sdk\`
3. 运行: \`node ${serverName}-mcp-server.js\`

## Claude Desktop 配置

将以下配置添加到 Claude Desktop 配置文件:
- macOS: \`~/Library/Application Support/Claude/claude_desktop_config.json\`
- Windows: \`%APPDATA%\\Claude\\claude_desktop_config.json\`

\`\`\`json
${configJson}
\`\`\`

${isPublic ? '' : `## 认证配置

此服务需要认证，请设置环境变量:
\`\`\`bash
export QIYUAI_AUTH_TOKEN=your_token
\`\`\`
`}
## 可用工具 (${actionInfos.length})

${actionInfos.map(a => `- \`${a.name}\`: ${a.displayName}`).join('\n')}
`;
}

/**
 * 创建 STDIO MCP 路由
 */
export function createStdioRoutes(): Elysia {
  const app = new Elysia({ name: "mcp-stdio-routes" });

  // 获取 STDIO MCP 服务器信息
  app.get(
    "/mcp/:id/stdio",
    async ({ params, set }) => {
      const [server] = await db.select().from(mcpServer).where(eq(mcpServer.id, params.id)).limit(1);
      if (!server) {
        set.status = 404;
        return { data: null, status: 404, message: "MCP server not found" };
      }

      const baseUrl = process.env.SERVER_BASE_URL || `http://localhost:${process.env.PORT || 3030}`;
      const serverName = server.name.toLowerCase().replace(/[^a-z0-9]+/g, '-');
      const actionInfos = buildActionInfos(server.actions);

      const serverJs = generateStdioServerJs(serverName, server.name, server.description, baseUrl, server.isPublic, actionInfos);
      const configJson = JSON.stringify({
        mcpServers: {
          [serverName]: {
            command: "node",
            args: [`${serverName}-mcp-server.js`],
            env: server.isPublic ? {} : { QIYUAI_AUTH_TOKEN: "<your-token>" },
          },
        },
      }, null, 2);
      const usage = generateUsage(serverName, server.name, server.isPublic, configJson, actionInfos);

      return { data: { serverName, serverJs, configJson, usage }, status: 200, message: "ok" };
    },
    {
      params: t.Object({ id: t.String() }),
      detail: { tags: ["MCP"], summary: "获取 STDIO MCP 服务器", description: "生成 STDIO 模式的 MCP 服务器 JS 文件" },
    }
  );

  // 下载 STDIO MCP 服务器
  app.get(
    "/mcp/:id/stdio/download",
    async ({ params, set }) => {
      const [server] = await db.select().from(mcpServer).where(eq(mcpServer.id, params.id)).limit(1);
      if (!server) {
        set.status = 404;
        return new Response("MCP server not found", { status: 404 });
      }

      const baseUrl = process.env.SERVER_BASE_URL || `http://localhost:${process.env.PORT || 3030}`;
      const serverName = server.name.toLowerCase().replace(/[^a-z0-9]+/g, '-');
      const actionInfos = buildActionInfos(server.actions);
      const serverJs = generateStdioServerJs(serverName, server.name, server.description, baseUrl, server.isPublic, actionInfos);

      set.headers["Content-Type"] = "application/javascript";
      set.headers["Content-Disposition"] = `attachment; filename="${serverName}-mcp-server.js"`;
      return new Response(serverJs);
    },
    {
      params: t.Object({ id: t.String() }),
      detail: { tags: ["MCP"], summary: "下载 STDIO MCP 服务器", description: "下载 STDIO 模式的 MCP 服务器 JS 文件" },
    }
  );

  return app;
}
