import { pgTable, uuid, varchar, timestamp, boolean, jsonb, text, char, integer, bigint, json, real, index, uniqueIndex, primaryKey } from "drizzle-orm/pg-core"
import { sql } from "drizzle-orm"



export const aiModel = pgTable("ai_model", {
	id: uuid().primaryKey().notNull(),
	createdById: uuid("created_by_id"),
	createdBy: varchar("created_by", { length: 64 }).notNull(),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
	updatedById: uuid("updated_by_id"),
	updatedBy: varchar("updated_by", { length: 64 }).notNull(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow().notNull(),
	isPublic: boolean("is_public").default(false).notNull(),
	allowedUserIds: jsonb("allowed_user_ids").default([]),
	allowedRoleIds: jsonb("allowed_role_ids").default([]),
	allowedDeptIds: jsonb("allowed_dept_ids").default([]),
	allowSubDepts: boolean("allow_sub_depts").default(false).notNull(),
	providerId: uuid("provider_id").notNull(),
	name: varchar({ length: 128 }).notNull(),
	modelId: varchar("model_id", { length: 128 }).notNull(),
	remark: text(),
	status: char({ length: 1 }).default('0'),
	supportTools: boolean("support_tools").default(false).notNull(),
	maxTokens: integer("max_tokens"),
	inputCapabilities: jsonb("input_capabilities").default({"file":false,"text":true,"audio":false,"image":false,"video":false}),
	outputCapabilities: jsonb("output_capabilities").default({"file":false,"text":true,"audio":false,"image":false,"video":false}),
});

export const aiProvider = pgTable("ai_provider", {
	id: uuid().primaryKey().notNull(),
	createdById: uuid("created_by_id"),
	createdBy: varchar("created_by", { length: 64 }).notNull(),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
	updatedById: uuid("updated_by_id"),
	updatedBy: varchar("updated_by", { length: 64 }).notNull(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow().notNull(),
	name: varchar({ length: 64 }).notNull(),
	baseUrl: varchar("base_url", { length: 512 }).notNull(),
	token: text().notNull(),
	remark: text(),
	status: char({ length: 1 }).default('0'),
});

export const aiTool = pgTable("ai_tool", {
	id: uuid().primaryKey().notNull(),
	createdById: uuid("created_by_id"),
	createdBy: varchar("created_by", { length: 64 }).notNull(),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
	updatedById: uuid("updated_by_id"),
	updatedBy: varchar("updated_by", { length: 64 }).notNull(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow().notNull(),
	isPublic: boolean("is_public").default(false).notNull(),
	allowedUserIds: jsonb("allowed_user_ids").default([]),
	allowedRoleIds: jsonb("allowed_role_ids").default([]),
	allowedDeptIds: jsonb("allowed_dept_ids").default([]),
	allowSubDepts: boolean("allow_sub_depts").default(false).notNull(),
	groupId: uuid("group_id"),
	name: varchar({ length: 64 }).notNull(),
	description: text(),
	inputSchema: jsonb("input_schema"),
	outputSchema: jsonb("output_schema"),
	isAsync: boolean("is_async").default(false).notNull(),
	implementation: text(),
	remark: text(),
	status: char({ length: 1 }).default('0'),
});

export const aiToolGroup = pgTable("ai_tool_group", {
	id: uuid().primaryKey().notNull(),
	createdById: uuid("created_by_id"),
	createdBy: varchar("created_by", { length: 64 }).notNull(),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
	updatedById: uuid("updated_by_id"),
	updatedBy: varchar("updated_by", { length: 64 }).notNull(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow().notNull(),
	name: varchar({ length: 64 }).notNull(),
	description: text(),
	icon: varchar({ length: 64 }),
	orderNum: integer("order_num").default(1).notNull(),
	remark: text(),
	status: char({ length: 1 }).default('0'),
});

export const knowledgeFileVersion = pgTable("knowledge_file_version", {
	id: uuid().primaryKey().notNull(),
	fileId: uuid("file_id").notNull(),
	versionNumber: varchar("version_number", { length: 32 }).notNull(),
	storageKey: varchar("storage_key", { length: 512 }).notNull(),
	bucket: varchar({ length: 128 }).notNull(),
	s3VersionId: varchar("s3_version_id", { length: 128 }),
	etag: varchar({ length: 128 }),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	size: bigint({ mode: "number" }).default(0).notNull(),
	changeLog: text("change_log"),
	createdById: uuid("created_by_id"),
	createdBy: varchar("created_by", { length: 64 }).notNull(),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
});

export const knowledgeFolder = pgTable("knowledge_folder", {
	id: uuid().primaryKey().notNull(),
	createdById: uuid("created_by_id"),
	createdBy: varchar("created_by", { length: 64 }).notNull(),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
	updatedById: uuid("updated_by_id"),
	updatedBy: varchar("updated_by", { length: 64 }).notNull(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow().notNull(),
	deletedById: uuid("deleted_by_id"),
	deletedBy: varchar("deleted_by", { length: 64 }),
	deletedAt: timestamp("deleted_at", { mode: 'string' }),
	isPublic: boolean("is_public").default(false).notNull(),
	parentId: uuid("parent_id"),
	name: varchar({ length: 255 }).notNull(),
	path: text().notNull(),
	description: text(),
	icon: varchar({ length: 64 }),
	color: varchar({ length: 32 }),
	orderNum: integer("order_num").default(0).notNull(),
});

export const knowledgeFile = pgTable("knowledge_file", {
	id: uuid().primaryKey().notNull(),
	createdById: uuid("created_by_id"),
	createdBy: varchar("created_by", { length: 64 }).notNull(),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
	updatedById: uuid("updated_by_id"),
	updatedBy: varchar("updated_by", { length: 64 }).notNull(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow().notNull(),
	deletedById: uuid("deleted_by_id"),
	deletedBy: varchar("deleted_by", { length: 64 }),
	deletedAt: timestamp("deleted_at", { mode: 'string' }),
	isPublic: boolean("is_public").default(false).notNull(),
	folderId: uuid("folder_id"),
	name: varchar({ length: 255 }).notNull(),
	originalName: varchar("original_name", { length: 255 }).notNull(),
	extension: varchar({ length: 32 }),
	mimeType: varchar("mime_type", { length: 128 }),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	size: bigint({ mode: "number" }).default(0).notNull(),
	storageKey: varchar("storage_key", { length: 512 }).notNull(),
	bucket: varchar({ length: 128 }).notNull(),
	region: varchar({ length: 64 }),
	etag: varchar({ length: 128 }),
	versionId: varchar("version_id", { length: 128 }),
	storageClass: varchar("storage_class", { length: 32 }).default('STANDARD'),
	metadata: jsonb().default({}),
	tags: jsonb().default([]),
	description: text(),
	processStatus: char("process_status", { length: 1 }).default('0'),
	processResult: jsonb("process_result"),
	downloadCount: integer("download_count").default(0).notNull(),
	status: char({ length: 1 }).default('0'),
	versionCount: integer("version_count").default(0).notNull(),
});

export const systemConfig = pgTable("system_config", {
	id: uuid().primaryKey().notNull(),
	createdById: uuid("created_by_id"),
	createdBy: varchar("created_by", { length: 64 }).notNull(),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
	updatedById: uuid("updated_by_id"),
	updatedBy: varchar("updated_by", { length: 64 }).notNull(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow().notNull(),
	name: varchar({ length: 128 }).notNull(),
	key: varchar({ length: 128 }).notNull(),
	value: varchar({ length: 512 }).notNull(),
	isSystem: boolean("is_system").default(true).notNull(),
});

export const systemDepartment = pgTable("system_department", {
	id: uuid().primaryKey().notNull(),
	createdById: uuid("created_by_id"),
	createdBy: varchar("created_by", { length: 64 }).notNull(),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
	updatedById: uuid("updated_by_id"),
	updatedBy: varchar("updated_by", { length: 64 }).notNull(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow().notNull(),
	deletedById: uuid("deleted_by_id"),
	deletedBy: varchar("deleted_by", { length: 64 }),
	deletedAt: timestamp("deleted_at", { mode: 'string' }),
	parentId: uuid("parent_id"),
	ancestors: text(),
	name: varchar({ length: 50 }).notNull(),
	orderNum: integer("order_num").default(1).notNull(),
	leader: varchar({ length: 20 }),
	phone: varchar({ length: 11 }),
	email: varchar({ length: 50 }),
	status: boolean().default(true).notNull(),
});

export const systemDict = pgTable("system_dict", {
	id: uuid().primaryKey().notNull(),
	createdById: uuid("created_by_id"),
	createdBy: varchar("created_by", { length: 64 }).notNull(),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
	updatedById: uuid("updated_by_id"),
	updatedBy: varchar("updated_by", { length: 64 }).notNull(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow().notNull(),
	deletedById: uuid("deleted_by_id"),
	deletedBy: varchar("deleted_by", { length: 64 }),
	deletedAt: timestamp("deleted_at", { mode: 'string' }),
	group: varchar({ length: 100 }).notNull(),
	label: varchar({ length: 100 }).notNull(),
	value: varchar({ length: 100 }).notNull(),
	sort: integer().default(0).notNull(),
	cssClass: varchar("css_class", { length: 100 }),
	listClass: varchar("list_class", { length: 100 }),
	isDefault: boolean("is_default").default(false).notNull(),
	status: char({ length: 1 }).default('0'),
	remark: varchar({ length: 512 }),
});

export const systemDictGroup = pgTable("system_dict_group", {
	createdById: uuid("created_by_id"),
	createdBy: varchar("created_by", { length: 64 }).notNull(),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
	updatedById: uuid("updated_by_id"),
	updatedBy: varchar("updated_by", { length: 64 }).notNull(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow().notNull(),
	key: varchar({ length: 100 }).primaryKey().notNull(),
	name: varchar({ length: 100 }).notNull(),
	status: char({ length: 1 }).default('0'),
	remark: varchar({ length: 512 }),
});

export const systemJob = pgTable("system_job", {
	id: uuid().primaryKey().notNull(),
	createdById: uuid("created_by_id"),
	createdBy: varchar("created_by", { length: 64 }).notNull(),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
	updatedById: uuid("updated_by_id"),
	updatedBy: varchar("updated_by", { length: 64 }).notNull(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow().notNull(),
	name: varchar({ length: 64 }).notNull(),
	group: varchar({ length: 64 }).default('DEFAULT').notNull(),
	invokeTarget: varchar("invoke_target", { length: 500 }).notNull(),
	cronExpression: varchar("cron_expression", { length: 255 }),
	misfirePolicy: char("misfire_policy", { length: 1 }).default('3'),
	concurrent: boolean().default(false).notNull(),
	status: char({ length: 1 }).default('0'),
	nextValidTime: timestamp("next_valid_time", { mode: 'string' }),
	remark: varchar({ length: 512 }),
});

export const systemJobLog = pgTable("system_job_log", {
	id: uuid().primaryKey().notNull(),
	createdById: uuid("created_by_id"),
	createdBy: varchar("created_by", { length: 64 }).notNull(),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
	updatedById: uuid("updated_by_id"),
	updatedBy: varchar("updated_by", { length: 64 }).notNull(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow().notNull(),
	jobName: varchar("job_name", { length: 64 }).notNull(),
	jobGroup: varchar("job_group", { length: 64 }).notNull(),
	invokeTarget: varchar("invoke_target", { length: 500 }).notNull(),
	jobMessage: text("job_message"),
	status: char({ length: 1 }).default('0'),
	exceptionInfo: text("exception_info"),
	startTime: timestamp("start_time", { mode: 'string' }),
	stopTime: timestamp("stop_time", { mode: 'string' }),
});

export const systemLoginInfo = pgTable("system_login_info", {
	id: uuid().primaryKey().notNull(),
	createdById: uuid("created_by_id"),
	createdBy: varchar("created_by", { length: 64 }).notNull(),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
	updatedById: uuid("updated_by_id"),
	updatedBy: varchar("updated_by", { length: 64 }).notNull(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow().notNull(),
	loginName: varchar("login_name", { length: 50 }),
	ipaddr: varchar({ length: 50 }),
	loginLocation: varchar("login_location", { length: 255 }),
	browser: varchar({ length: 50 }),
	os: varchar({ length: 50 }),
	status: char({ length: 1 }).default('0'),
	msg: text(),
	loginTime: timestamp("login_time", { mode: 'string' }).defaultNow(),
});

export const systemMenu = pgTable("system_menu", {
	id: uuid().primaryKey().notNull(),
	createdById: uuid("created_by_id"),
	createdBy: varchar("created_by", { length: 64 }).notNull(),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
	updatedById: uuid("updated_by_id"),
	updatedBy: varchar("updated_by", { length: 64 }).notNull(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow().notNull(),
	name: varchar({ length: 50 }).notNull(),
	parentId: uuid("parent_id"),
	orderNum: integer("order_num").default(1).notNull(),
	path: varchar({ length: 200 }),
	type: varchar({ length: 1 }).notNull(),
	visible: boolean().default(true).notNull(),
	isCache: boolean("is_cache").default(true).notNull(),
	isFrame: boolean("is_frame").default(false).notNull(),
	perms: varchar({ length: 100 }),
	icon: varchar({ length: 64 }),
	component: varchar({ length: 255 }),
	remark: varchar({ length: 512 }),
});

export const systemNotice = pgTable("system_notice", {
	id: uuid().primaryKey().notNull(),
	createdById: uuid("created_by_id"),
	createdBy: varchar("created_by", { length: 64 }).notNull(),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
	updatedById: uuid("updated_by_id"),
	updatedBy: varchar("updated_by", { length: 64 }).notNull(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow().notNull(),
	title: varchar({ length: 50 }).notNull(),
	type: varchar({ length: 1 }).notNull(),
	content: text().notNull(),
	status: char({ length: 1 }).default('0'),
});

export const systemOperationLog = pgTable("system_operation_log", {
	id: uuid().primaryKey().notNull(),
	title: varchar({ length: 255 }).notNull(),
	businessType: integer("business_type"),
	businessTypes: text("business_types"),
	method: varchar({ length: 255 }),
	requestMethod: varchar("request_method", { length: 50 }),
	type: integer(),
	name: varchar({ length: 50 }),
	departmentName: varchar("department_name", { length: 50 }),
	url: varchar({ length: 255 }),
	ip: varchar({ length: 50 }),
	location: varchar({ length: 255 }),
	param: text(),
	jsonResult: text("json_result"),
	status: char({ length: 1 }).default('0'),
	errorMsg: text("error_msg"),
	time: timestamp({ mode: 'string' }),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	costTime: bigint("cost_time", { mode: "number" }),
});

export const systemPost = pgTable("system_post", {
	id: uuid().primaryKey().notNull(),
	createdById: uuid("created_by_id"),
	createdBy: varchar("created_by", { length: 64 }).notNull(),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
	updatedById: uuid("updated_by_id"),
	updatedBy: varchar("updated_by", { length: 64 }).notNull(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow().notNull(),
	code: varchar({ length: 64 }).notNull(),
	name: varchar({ length: 50 }).notNull(),
	sort: varchar({ length: 10 }).notNull(),
	status: char({ length: 1 }).default('0'),
	deletedById: uuid("deleted_by_id"),
	deletedBy: varchar("deleted_by", { length: 64 }),
	deletedAt: timestamp("deleted_at", { mode: 'string' }),
});

export const systemRole = pgTable("system_role", {
	id: uuid().primaryKey().notNull(),
	createdById: uuid("created_by_id"),
	createdBy: varchar("created_by", { length: 64 }).notNull(),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
	updatedById: uuid("updated_by_id"),
	updatedBy: varchar("updated_by", { length: 64 }).notNull(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow().notNull(),
	deletedById: uuid("deleted_by_id"),
	deletedBy: varchar("deleted_by", { length: 64 }),
	deletedAt: timestamp("deleted_at", { mode: 'string' }),
	name: varchar({ length: 30 }).notNull(),
	key: varchar({ length: 100 }).notNull(),
	sort: varchar({ length: 10 }).notNull(),
	dataScope: varchar("data_scope", { length: 1 }),
	status: char({ length: 1 }).default('0'),
	flag: boolean().default(false),
	menuIds: jsonb("menu_ids").default([]),
	deptIds: jsonb("dept_ids").default([]),
	permissions: json().default([]),
});

export const systemRoleDepartment = pgTable("system_role_department", {
	roleId: uuid("role_id").notNull(),
	departmentId: uuid("department_id").notNull(),
});

export const systemRoleMenu = pgTable("system_role_menu", {
	roleId: uuid("role_id").notNull(),
	menuId: uuid("menu_id").notNull(),
});

export const systemUser = pgTable("system_user", {
	id: uuid().primaryKey().notNull(),
	createdById: uuid("created_by_id"),
	createdBy: varchar("created_by", { length: 64 }).notNull(),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
	updatedById: uuid("updated_by_id"),
	updatedBy: varchar("updated_by", { length: 64 }).notNull(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow().notNull(),
	deletedById: uuid("deleted_by_id"),
	deletedBy: varchar("deleted_by", { length: 64 }),
	deletedAt: timestamp("deleted_at", { mode: 'string' }),
	deptId: uuid("dept_id"),
	parentId: uuid("parent_id"),
	roleId: uuid("role_id"),
	loginName: varchar("login_name", { length: 30 }).notNull(),
	name: varchar({ length: 30 }).notNull(),
	userType: varchar("user_type", { length: 10 }),
	email: varchar({ length: 50 }),
	phonenumber: varchar({ length: 11 }),
	sex: varchar({ length: 1 }),
	avatar: varchar({ length: 255 }),
	password: varchar({ length: 255 }),
	salt: varchar({ length: 255 }),
	status: varchar({ length: 1 }),
	loginIp: varchar("login_ip", { length: 50 }),
	loginDate: timestamp("login_date", { mode: 'string' }),
	pwdUpdateDate: timestamp("pwd_update_date", { mode: 'string' }),
	roleIds: jsonb("role_ids"),
	postIds: jsonb("post_ids"),
	permissions: jsonb(),
});

export const systemUserPost = pgTable("system_user_post", {
	userId: uuid("user_id").notNull(),
	postId: uuid("post_id").notNull(),
});

export const systemUserRole = pgTable("system_user_role", {
	userId: uuid("user_id").notNull(),
	roleId: uuid("role_id").notNull(),
});

export const systemToken = pgTable("system_token", {
	id: uuid().primaryKey().notNull(),
	createdById: uuid("created_by_id"),
	createdBy: varchar("created_by", { length: 64 }).notNull(),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
	updatedById: uuid("updated_by_id"),
	updatedBy: varchar("updated_by", { length: 64 }).notNull(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow().notNull(),
	userId: uuid("user_id").notNull(),
	jti: varchar({ length: 64 }).notNull(),
	sub: varchar({ length: 128 }).notNull(),
	iat: timestamp({ mode: 'string' }).defaultNow().notNull(),
	exp: timestamp({ mode: 'string' }).notNull(),
	scopes: jsonb().default([]),
	isRevoked: boolean("is_revoked").default(false).notNull(),
	revokedAt: timestamp("revoked_at", { mode: 'string' }),
});

export const aiAgent = pgTable("ai_agent", {
	id: uuid().primaryKey().notNull(),
	createdById: uuid("created_by_id"),
	createdBy: varchar("created_by", { length: 64 }).notNull(),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
	updatedById: uuid("updated_by_id"),
	updatedBy: varchar("updated_by", { length: 64 }).notNull(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow().notNull(),
	isPublic: boolean("is_public").default(false).notNull(),
	allowedUserIds: jsonb("allowed_user_ids").default([]),
	allowedRoleIds: jsonb("allowed_role_ids").default([]),
	allowedDeptIds: jsonb("allowed_dept_ids").default([]),
	allowSubDepts: boolean("allow_sub_depts").default(false).notNull(),
	name: varchar({ length: 64 }).notNull(),
	description: text(),
	avatar: varchar({ length: 255 }),
	color: varchar({ length: 32 }),
	providerId: uuid("provider_id").notNull(),
	modelId: uuid("model_id").notNull(),
	systemPrompt: text("system_prompt"),
	skillIds: jsonb("skill_ids").default([]),
	toolIds: jsonb("tool_ids").default([]),
	temperature: real().default(0.7),
	supportLoop: boolean("support_loop").default(false).notNull(),
	maxLoops: jsonb("max_loops").default(10),
	remark: text(),
	status: char({ length: 1 }).default('0'),
	contextStrategy: varchar("context_strategy", { length: 64 }),
});

export const aiAgentMessage = pgTable("ai_agent_message", {
	id: uuid().primaryKey().notNull(),
	sessionId: uuid("session_id").notNull(),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	msgSeq: bigint("msg_seq", { mode: "number" }).notNull(),
	role: varchar({ length: 16 }).notNull(),
	content: jsonb(),
	contentType: char("content_type", { length: 2 }).default('01').notNull(),
	toolCalls: jsonb("tool_calls"),
	toolResults: jsonb("tool_results"),
	tokenCount: integer("token_count").default(0),
	modelId: uuid("model_id"),
	latencyMs: integer("latency_ms"),
	finishReason: varchar("finish_reason", { length: 32 }),
	extra: jsonb().default({}),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("idx_ai_agent_message_created_at").using("btree", table.createdAt.asc().nullsLast().op("timestamp_ops")),
	index("idx_ai_agent_message_session_seq").using("btree", table.sessionId.asc().nullsLast().op("int8_ops"), table.msgSeq.asc().nullsLast().op("int8_ops")),
]);

export const aiAgentSession = pgTable("ai_agent_session", {
	id: uuid().primaryKey().notNull(),
	createdById: uuid("created_by_id"),
	createdBy: varchar("created_by", { length: 64 }).notNull(),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
	updatedById: uuid("updated_by_id"),
	updatedBy: varchar("updated_by", { length: 64 }).notNull(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow().notNull(),
	deletedById: uuid("deleted_by_id"),
	deletedBy: varchar("deleted_by", { length: 64 }),
	deletedAt: timestamp("deleted_at", { mode: 'string' }),
	agentId: uuid("agent_id").notNull(),
	userId: uuid("user_id").notNull(),
	title: varchar({ length: 255 }),
	summary: text(),
	messageCount: integer("message_count").default(0).notNull(),
	tokenUsage: jsonb("token_usage").default({"totalTokens":0,"promptTokens":0,"completionTokens":0}),
	lastMessageAt: timestamp("last_message_at", { mode: 'string' }),
	isArchived: boolean("is_archived").default(false).notNull(),
	isPinned: boolean("is_pinned").default(false).notNull(),
	extra: jsonb().default({}),
	status: char({ length: 1 }).default('0'),
}, (table) => [
	index("idx_ai_agent_session_agent").using("btree", table.agentId.asc().nullsLast().op("uuid_ops")),
	index("idx_ai_agent_session_last_message").using("btree", table.lastMessageAt.asc().nullsLast().op("timestamp_ops")),
	index("idx_ai_agent_session_user").using("btree", table.userId.asc().nullsLast().op("uuid_ops")),
]);

export const imConversation = pgTable("im_conversation", {
	id: uuid().primaryKey().notNull(),
	createdById: uuid("created_by_id"),
	createdBy: varchar("created_by", { length: 64 }).notNull(),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
	updatedById: uuid("updated_by_id"),
	updatedBy: varchar("updated_by", { length: 64 }).notNull(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow().notNull(),
	deletedById: uuid("deleted_by_id"),
	deletedBy: varchar("deleted_by", { length: 64 }),
	deletedAt: timestamp("deleted_at", { mode: 'string' }),
	type: char({ length: 1 }).default('1').notNull(),
	name: varchar({ length: 128 }),
	avatar: varchar({ length: 512 }),
	ownerId: uuid("owner_id"),
	lastMessageId: uuid("last_message_id"),
	lastMessageAt: timestamp("last_message_at", { mode: 'string' }),
	memberCount: integer("member_count").default(0).notNull(),
	maxMembers: integer("max_members").default(500),
	isTop: boolean("is_top").default(false).notNull(),
	isMuted: boolean("is_muted").default(false).notNull(),
	announcement: text(),
	extra: jsonb().default({}),
	status: char({ length: 1 }).default('0'),
});

export const imMessage = pgTable("im_message", {
	id: uuid().primaryKey().notNull(),
	conversationId: uuid("conversation_id").notNull(),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	msgSeq: bigint("msg_seq", { mode: "number" }).notNull(),
	senderId: uuid("sender_id").notNull(),
	msgType: char("msg_type", { length: 2 }).default('01').notNull(),
	content: jsonb().notNull(),
	replyToId: uuid("reply_to_id"),
	forwardFromId: uuid("forward_from_id"),
	atUserIds: jsonb("at_user_ids").default([]),
	isRecalled: boolean("is_recalled").default(false).notNull(),
	recalledAt: timestamp("recalled_at", { mode: 'string' }),
	recalledById: uuid("recalled_by_id"),
	extra: jsonb().default({}),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("idx_im_message_conversation_seq").using("btree", table.conversationId.asc().nullsLast().op("uuid_ops"), table.msgSeq.asc().nullsLast().op("int8_ops")),
	index("idx_im_message_created_at").using("btree", table.createdAt.asc().nullsLast().op("timestamp_ops")),
	index("idx_im_message_sender").using("btree", table.senderId.asc().nullsLast().op("uuid_ops")),
]);

export const imTempFile = pgTable("im_temp_file", {
	id: uuid().primaryKey().notNull(),
	createdById: uuid("created_by_id"),
	createdBy: varchar("created_by", { length: 64 }).notNull(),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
	updatedById: uuid("updated_by_id"),
	updatedBy: varchar("updated_by", { length: 64 }).notNull(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow().notNull(),
	conversationId: uuid("conversation_id"),
	messageId: uuid("message_id"),
	name: varchar({ length: 255 }).notNull(),
	originalName: varchar("original_name", { length: 255 }).notNull(),
	extension: varchar({ length: 32 }),
	mimeType: varchar("mime_type", { length: 128 }),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	size: bigint({ mode: "number" }).default(0).notNull(),
	storageKey: varchar("storage_key", { length: 512 }).notNull(),
	bucket: varchar({ length: 128 }).notNull(),
	region: varchar({ length: 64 }),
	etag: varchar({ length: 128 }),
	expiresAt: timestamp("expires_at", { mode: 'string' }),
	metadata: jsonb().default({}),
	status: char({ length: 1 }).default('0'),
}, (table) => [
	index("idx_im_temp_file_conversation").using("btree", table.conversationId.asc().nullsLast().op("uuid_ops")),
	index("idx_im_temp_file_expires").using("btree", table.expiresAt.asc().nullsLast().op("timestamp_ops")),
	index("idx_im_temp_file_message").using("btree", table.messageId.asc().nullsLast().op("uuid_ops")),
]);

export const knowledgeResourcePermission = pgTable("knowledge_resource_permission", {
	id: uuid().primaryKey().notNull(),
	createdById: uuid("created_by_id"),
	createdBy: varchar("created_by", { length: 64 }).notNull(),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
	updatedById: uuid("updated_by_id"),
	updatedBy: varchar("updated_by", { length: 64 }).notNull(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow().notNull(),
	resourceType: varchar("resource_type", { length: 16 }).notNull(),
	resourceId: uuid("resource_id").notNull(),
	granteeType: varchar("grantee_type", { length: 16 }).notNull(),
	granteeId: uuid("grantee_id").notNull(),
	permissionLevel: char("permission_level", { length: 1 }).default('r').notNull(),
}, (table) => [
	uniqueIndex("resource_permission_unique_idx").using("btree", table.resourceType.asc().nullsLast().op("uuid_ops"), table.resourceId.asc().nullsLast().op("uuid_ops"), table.granteeType.asc().nullsLast().op("text_ops"), table.granteeId.asc().nullsLast().op("uuid_ops")),
]);

export const aiSkill = pgTable("ai_skill", {
	id: uuid().primaryKey().notNull(),
	createdById: uuid("created_by_id"),
	createdBy: varchar("created_by", { length: 64 }).notNull(),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
	updatedById: uuid("updated_by_id"),
	updatedBy: varchar("updated_by", { length: 64 }).notNull(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow().notNull(),
	isPublic: boolean("is_public").default(false).notNull(),
	allowedUserIds: jsonb("allowed_user_ids").default([]),
	allowedRoleIds: jsonb("allowed_role_ids").default([]),
	allowedDeptIds: jsonb("allowed_dept_ids").default([]),
	allowSubDepts: boolean("allow_sub_depts").default(false).notNull(),
	name: varchar({ length: 64 }).notNull(),
	parentId: uuid("parent_id"),
	isGroup: boolean("is_group").default(false).notNull(),
	orderNum: integer("order_num").default(1).notNull(),
	icon: varchar({ length: 64 }),
	description: text(),
	folderId: uuid("folder_id"),
	remark: text(),
	status: char({ length: 1 }).default('0'),
	fileId: uuid("file_id"),
	isA2A: boolean("is_a2a").default(false).notNull(),
});

export const imConversationRead = pgTable("im_conversation_read", {
	conversationId: uuid("conversation_id").notNull(),
	userId: uuid("user_id").notNull(),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	lastReadSeq: bigint("last_read_seq", { mode: "number" }).default(0).notNull(),
	lastReadAt: timestamp("last_read_at", { mode: 'string' }).defaultNow().notNull(),
	unreadCount: integer("unread_count").default(0).notNull(),
}, (table) => [
	index("idx_im_conversation_read_user").using("btree", table.userId.asc().nullsLast().op("uuid_ops")),
	primaryKey({ columns: [table.conversationId, table.userId], name: "im_conversation_read_conversation_id_user_id_pk"}),
]);

export const imConversationHidden = pgTable("im_conversation_hidden", {
	conversationId: uuid("conversation_id").notNull(),
	userId: uuid("user_id").notNull(),
	isHidden: boolean("is_hidden").default(true).notNull(),
	hiddenAt: timestamp("hidden_at", { mode: 'string' }).defaultNow().notNull(),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	primaryKey({ columns: [table.conversationId, table.userId], name: "im_conversation_hidden_conversation_id_user_id_pk"}),
]);

export const imGroupMember = pgTable("im_group_member", {
	conversationId: uuid("conversation_id").notNull(),
	userId: uuid("user_id").notNull(),
	nickname: varchar({ length: 64 }),
	role: char({ length: 1 }).default('0').notNull(),
	invitedById: uuid("invited_by_id"),
	joinedAt: timestamp("joined_at", { mode: 'string' }).defaultNow().notNull(),
	isMuted: boolean("is_muted").default(false).notNull(),
	mutedUntil: timestamp("muted_until", { mode: 'string' }),
	extra: jsonb().default({}),
}, (table) => [
	index("idx_im_group_member_user").using("btree", table.userId.asc().nullsLast().op("uuid_ops")),
	primaryKey({ columns: [table.conversationId, table.userId], name: "im_group_member_conversation_id_user_id_pk"}),
]);
